from flask import Flask, request, jsonify, render_template
from flask_cors import CORS
import requests
import re
import sys

app = Flask(__name__)
CORS(app)


# ✅ Configure your Gemini API Key
GEMINI_API_KEY = "AIzaSyAvzL_13CNVzpP0KVeGiwUEvdEWl3Ro5NU"
GEMINI_API_URL = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"


def extract_probability(text):
    if not text:
        return None
    match = re.search(r"(\d{1,3}) ?%", text)
    if match:
        prob = int(match.group(1))
        if 0 <= prob <= 100:
            return prob
    low_text = text.lower()
    if any(word in low_text for word in ["very likely", "highly likely", "almost certainly"]):
        return 90
    if any(word in low_text for word in ["likely", "probably"]):
        return 75
    if any(word in low_text for word in ["possibly", "maybe"]):
        return 50
    if any(word in low_text for word in ["unlikely", "doubtful"]):
        return 25
    if any(word in low_text for word in ["very unlikely", "almost certainly not"]):
        return 10
    return None


def call_gemini_api(prompt):
    headers = {"Content-Type": "application/json"}
    params = {"key": GEMINI_API_KEY}
    data = {
        "contents": [
            {"parts": [{"text": prompt}]}
        ]
    }
    response = requests.post(GEMINI_API_URL, headers=headers, params=params, json=data)
    print("Gemini raw response:", response.text, file=sys.stderr)
    if response.status_code == 200:
        resp_json = response.json()
        try:
            return resp_json["candidates"][0]["content"]["parts"][0]["text"]
        except Exception as e:
            return f"Gemini API error: Could not parse response: {e}"
    else:
        return f"Gemini API error: {response.text}"


@app.route("/")
def home():
    return render_template("home.html")


@app.route("/check")
def check():
    return render_template("check.html")


@app.route("/extension")
def extension_page():
    return render_template("extension.html")


@app.route('/about')
def about_page():
    return render_template('about.html')


@app.route('/contact')
def contact_page():
    return render_template('contact.html')


@app.route('/patent')
def patent_page():
    return render_template('patent.html')


@app.route("/process", methods=["POST"])
def process():
    try:
        user_input = request.form.get("user_input", "").strip()
        user_link = request.form.get("user_link", "").strip()

        lang = request.form.get('lang', 'en')
        if not user_input and not user_link:
            msg = "Please provide text, an image, or a link."
            if lang == 'hi':
                msg = "कृपया कुछ पाठ, एक छवि, या एक लिंक प्रदान करें।"
            return jsonify({"reply": msg}), 400

        lang_instruction = "Respond in Hindi." if lang == 'hi' else "Respond in English."

        if user_link:
            prompt = f"Analyze the content of this link and check for facts or misinformation: {user_link}. Estimate the probability (in percentage) that the news is truthful. {lang_instruction} Respond with your reasoning and a probability percentage."
        else:
            prompt = f"Analyze the following message for facts or misinformation. Estimate the probability (in percentage) that the news is truthful. {lang_instruction} Respond with your reasoning and a probability percentage. Message: {user_input}"

        text = call_gemini_api(prompt)
        prob = extract_probability(text)
        reply = text or ""
        if prob is not None:
            reply += f"\n\nEstimated Truth Probability: {prob}%"
        if not reply.strip():
            reply = "No response from Gemini API."

        return jsonify({"reply": reply})

    except Exception as e:
        print("Flask exception in /process:", e, file=sys.stderr)
        return jsonify({"reply": f"Flask error: {e}"}), 500


@app.route('/ai-check', methods=['POST'])
def ai_check():
    """Simple JSON API for the browser extension. Accepts {text:..., image_url:...} and returns ai_percent and message."""
    try:
        data = request.get_json(force=True)
        text = (data.get('text') if data else None) or ''
        image_url = (data.get('image_url') if data else None) or ''

        if not text and not image_url:
            return jsonify({'error': 'Provide text or image_url'}), 400

        # Build a short prompt for Gemini
        if text:
            prompt = f"Determine the likelihood that the following text was generated by AI. Provide a short verdict and a percentage likelihood. Text: {text}"
        else:
            prompt = f"Determine the likelihood that the image at this URL was generated or heavily manipulated by AI. Provide a short verdict and a percentage likelihood. Image URL: {image_url}"

        resp_text = call_gemini_api(prompt)
        percent = extract_probability(resp_text)
        if percent is None:
            # fallback heuristic: look for 'ai' or 'generated' words
            lower = (resp_text or '').lower()
            percent = 75 if 'ai' in lower or 'generated' in lower else 40

        message = resp_text.split('\n')[0] if resp_text else 'No verdict'
        return jsonify({'ai_percent': percent, 'message': message})

    except Exception as e:
        print('Error in /ai-check:', e, file=sys.stderr)
        return jsonify({'error': str(e)}), 500


if __name__ == "__main__":
    import os
    port = int(os.environ.get("PORT", 5001))
    app.run(debug=True, port=port)

